INSERT INTO TCLIENTE (APELLIDO, CEDULA, NOMBRE, TELEFONO, PAISRESIDENCIA,PAISNACIMIENTO,DIRECCION,ESTADO) VALUES ('PEREZ', '1', 'ROBERTO', '093939393', 'EC','EC','QUITO',true);
INSERT INTO TCLIENTE (APELLIDO, CEDULA, NOMBRE, TELEFONO, PAISRESIDENCIA,PAISNACIMIENTO,DIRECCION,ESTADO) VALUES ('SANCHEZ', '2', 'RAUL', '093223333', 'CR','CR','ALAJUELA',true);
INSERT INTO TCLIENTE (APELLIDO, CEDULA, NOMBRE, TELEFONO, PAISRESIDENCIA,PAISNACIMIENTO,DIRECCION,ESTADO) VALUES ('SANCHEZ', '3', 'PAUL', '093223334', 'CR','CR','SAN JOSE',false);
